### ISSUE TITLE
Could not load on Xcode

### ISSUE THREAD

**Issue by dreamdev21** [ismnoiet/react-native-range-slider#1]
I have imported this following on doc, but Xcode not loading RnageSlider.xcodeproj

**Comment by ismnoiet** [comment]
Can you tell me which version of Xcode you're using and which error you're getting.

**Comment by dreamdev21** [comment]
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.11.2
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: ^0.55.2 => 0.55.4
![capture](https://user-images.githubusercontent.com/29256561/41546233-6af8c71e-731d-11e8-8b75-237eb1266ef1.PNG)

**Comment by ismnoiet** [comment]
This is because I built the module using Xcode 9.3, I solved that issue.
please  reinstall the latest version `0.0.6`(published recently) it should fix this problem for you.

If you run into other issues related to this module don't hesitate to open an issue for that.

And don't forget to star the repo if you like the module and think it is useful, so I keep open sourcing other cool stuff :)

**Comment by dreamdev21** [comment]
Thank you for your quick update.
Xcode issue is solved but still this error is here.
![simulator screen shot - iphone 7 plus - 2018-06-18 at 08 58 10](https://user-images.githubusercontent.com/29256561/41547741-56e72820-7321-11e8-960b-710d85ede1bd.png)

**Comment by ismnoiet** [comment]
You're getting this error because I assume you already have `prop-types` installed(recommended by facebook also) on your project dependencies. to solve that just install that module using:

```
npm install --save prop-types
```

If you still have issues after installing the module let me know.

**Comment by dreamdev21** [comment]
Tried above solution, unfortunately no succeed.
Issue is not solved.

**Comment by ismnoiet** [comment]
ok, for now try to open `node_modules/react-native-range-slider/index.js` and comment the propType portion of the code : 
```
RangeSlider.propTypes = {....}
```
and let me know if it is working.

**Comment by dreamdev21** [comment]
It works!!!
Will wait updated version here.
Thanks.

**Comment by ismnoiet** [comment]
Great, will update the version soon. just don't forget to 🌟 the repo.

**Comment by ismnoiet** [comment]
@webmasterdragon Please update to the latest version(currently `0.0.7`) and let me know if it is working correctly.

**Comment by dreamdev21** [comment]
Now it's working.
Hope this one is become top react-native range slider package.
